### ISSUE TITLE
typo issue

### ISSUE THREAD

**Issue by VenomFate-619** [alok722/namaste-javascript-notes#12]
<img width="130" alt="image" src="https://user-images.githubusercontent.com/67755128/198992084-def30a6e-199e-4407-9349-f12d39cd5d8b.png">

Present in `Episode 7 : The Scope Chain, Scope & Lexical Environment`

**Comment by dinesh-14** [comment]
Can you assign this issue ?

**Comment by alok722** [comment]
Fix has already been raised at #11
