### ISSUE TITLE
Update the file name - FROM -> notes/lectures-22.md TO notes/lecture-22.md

### ISSUE THREAD

**Issue by pixlboy** [alok722/namaste-javascript-notes#18]
Please change the file name :

FROM --> **notes/lectures-22.md** TO **notes/lecture-22.md**

The link is currently broken when you click on main page.

**Comment by Suraj-kumar00** [comment]
Hello Rachit Garg, as I saw this issue is open so can I contribute to this?

**Comment by alok722** [comment]
Addressed!
thanks!
