### ISSUE TITLE
Episode 1:  Execution Context

### ISSUE THREAD

**Issue by Ashishyadav07** [alok722/namaste-javascript-notes#20]
You wrote opposite definition in synchronous , single threaded language.

It will be - 

Single-threaded:- One command at a time.
Synchronous:- In a specific synchronous order.

**Comment by alok722** [comment]
thanks for highlighting it, it is correct over [here](https://github.com/alok722/namaste-javascript-notes/blob/master/notes/lecture-1.md#episode-1--execution-context)
I will rectify this in `lectures.md` too.
