### ISSUE TITLE
Wrong text in GIF's  for the Callback queue. Episode 15 : Asynchronous JavaScript & EVENT LOOP from scratch 

### ISSUE THREAD

**Issue by asifvora** [alok722/namaste-javascript-notes#3]
GIF's need to update for the callback queue text.

![Namaste JavaScript](https://user-images.githubusercontent.com/26271039/128171309-4b1adce4-dac3-4c24-9ce5-9f74e7ed1d1c.png)

There are two types of queue.
- Microtask queue
- Callback queue

**Comment by alok722** [comment]
I believe Callback queue are also known as Macrotask queue.

Read more at:

* https://javascript.info/event-loop
* https://stackoverflow.com/questions/25915634/difference-between-microtask-and-macrotask-within-an-event-loop-context

**Comment by alok722** [comment]
closing the issue as I didn't get any reply back.
